import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from '@/hooks/use-toast';
import { useEffect, useMemo } from 'react';
import { useAreas } from '@/hooks/queries/useAreas';
import { useCreateTable } from '@/hooks/queries/useTables';
import { TableDTO } from '@/dto/table.dto';

const tableSchema = z.object({
  capacity: z.coerce.number().min(1, 'Capacity must be at least 1'),
  areaId: z.string().min(1, 'Area is required'),
});

type TableFormData = z.infer<typeof tableSchema>;

interface TableDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  branchId: string;
  table?: TableDTO;
  existingTables?: TableDTO[]; // Thêm prop để truyền danh sách tables hiện có
}

export const TableDialog = ({ open, onOpenChange, branchId, table, existingTables = [] }: TableDialogProps) => {
  const { data: areasData } = useAreas(branchId);
  const areas = areasData || [];
  const createTableMutation = useCreateTable();

  // Function để extract số từ table tag (ví dụ: "Table 1" -> 1, "Table 10" -> 10)
  const extractTableNumber = (tag: string): number | null => {
    const match = tag.match(/(?:table|bàn)\s*(\d+)/i);
    return match ? parseInt(match[1], 10) : null;
  };

  // Tính số bàn tiếp theo dựa trên existing tables
  const getNextTableNumber = useMemo(() => {
    if (existingTables.length === 0) {
      return 1; // Chưa có bàn nào, bắt đầu từ Table 1
    }
    
    // Extract tất cả số từ table tags
    const tableNumbers = existingTables
      .map(table => extractTableNumber(table.tag))
      .filter((num): num is number => num !== null);
    
    if (tableNumbers.length === 0) {
      return 1; // Không tìm thấy số nào, bắt đầu từ 1
    }
    
    // Tìm số lớn nhất và +1
    const maxNumber = Math.max(...tableNumbers);
    return maxNumber + 1;
  }, [existingTables]);

  // Generate table tag tự động
  const autoGeneratedTag = useMemo(() => {
    return `Table ${getNextTableNumber}`;
  }, [getNextTableNumber]);

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
    setValue,
    watch,
  } = useForm<TableFormData>({
    resolver: zodResolver(tableSchema),
    defaultValues: {
      capacity: 4,
      areaId: '',
    },
  });

  const selectedAreaId = watch('areaId');

  // Fix infinite loop: use useMemo to memoize firstAreaId
  // Only recompute when areas array actually changes (by checking first area's ID)
  const firstAreaId = useMemo(() => {
    return areas.length > 0 ? areas[0].areaId : '';
  }, [areas.length > 0 ? areas[0]?.areaId : null]);

  useEffect(() => {
    if (!open) {
      return; // Don't reset when dialog is closed
    }
    
    if (table) {
      reset({
        capacity: table.capacity,
        areaId: table.areaId || firstAreaId,
      });
    } else {
      reset({
        capacity: 4,
        areaId: firstAreaId,
      });
    }
  }, [table, open, firstAreaId, reset]);

  const onSubmit = async (data: TableFormData) => {
    try {
      if (table) {
        // TODO: Implement update table API if needed
        toast({
          title: 'Update not implemented',
          description: 'Table update functionality will be available soon.',
          variant: 'destructive',
        });
      } else {
        // Sử dụng auto-generated tag thay vì từ form
        await createTableMutation.mutateAsync({
          areaId: data.areaId,
          tag: autoGeneratedTag, // Tự động generate table name
          capacity: data.capacity,
        });
        toast({
          title: 'Table Added',
          description: `Table "${autoGeneratedTag}" created successfully with QR code.`,
        });
        onOpenChange(false);
        reset();
      }
    } catch (error: any) {
      const errorMessage = error?.response?.data?.message || error?.message || 'Failed to create table';
      toast({
        variant: 'destructive',
        title: 'Error',
        description: errorMessage,
      });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{table ? 'Edit Table' : 'Add Table'}</DialogTitle>
          <DialogDescription>
            {table ? 'Update table details' : 'Create a new table with auto-generated QR code'}
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="areaId">Area *</Label>
            <Select
              value={selectedAreaId}
              onValueChange={(value) => setValue('areaId', value)}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select an area" />
              </SelectTrigger>
              <SelectContent>
                {areas.length === 0 ? (
                  <SelectItem value="" disabled>No areas available</SelectItem>
                ) : (
                  areas.map((area) => (
                    <SelectItem key={area.areaId} value={area.areaId}>
                      {area.name}
                    </SelectItem>
                  ))
                )}
              </SelectContent>
            </Select>
            {errors.areaId && (
              <p className="text-sm text-destructive">{errors.areaId.message}</p>
            )}
            {areas.length === 0 && (
              <p className="text-sm text-muted-foreground">Please create an area first before adding tables.</p>
            )}
          </div>

          {/* Hiển thị table name sẽ được tự động generate */}
          <div className="space-y-2">
            <Label>Table Name</Label>
            <div className="px-3 py-2 bg-muted rounded-md text-sm font-medium">
              {autoGeneratedTag}
            </div>
            <p className="text-xs text-muted-foreground">
              Table name will be automatically generated
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="capacity">Capacity (people) *</Label>
            <Input {...register('capacity')} id="capacity" type="number" min="1" />
            {errors.capacity && (
              <p className="text-sm text-destructive">{errors.capacity.message}</p>
            )}
          </div>

          <div className="flex justify-end gap-3 pt-4">
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={areas.length === 0 || createTableMutation.isPending}>
              {createTableMutation.isPending ? 'Creating...' : table ? 'Update' : 'Create'} Table
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};
