name: CI - Build Test

on:
  push:
    branches: [ "dev", "dev-*" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    # if want to test connect db
    # services:
    #   postgres:
    #     image: postgres:16
    #     env:
    #       POSTGRES_USER: test
    #       POSTGRES_PASSWORD: test
    #       POSTGRES_DB: app
    #     ports:
    #       - 5432:5432
    #     # Set health checks to wait until postgres has started
    #     options: >-
    #       --health-cmd "pg_isready -U test" 
    #       --health-interval 10s 
    #       --health-timeout 5s 
    #       --health-retries 5
    
    env:
      DB_URL: jdbc:postgresql://localhost:5432/app
      DB_USERNAME: test
      
      JWT_SIGNER_KEY: testSignerKey
      JWT_ISSUER: test
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
      
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Build backend JAR
        working-directory: ./backend
        run: |
          mvn clean package -DskipTests

      - name: Verify build outputs
        run: |
          ls -l frontend/dist
          ls -l backend/target/*.jar